### ISSUE TITLE
- [ ] Realizar Prototipo baja o mediana fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#10]

**Comment by JohnFlorez25** [comment]
Se deben complementar los prototipos de acuerdo a las recomendaciones brindadas esto con el fin de ampliar y evidenciar las funcionalidades de la aplicación.

**Comment by aleospiria** [comment]
https://marvelapp.com/prototype/5bh2i85
