### ISSUE TITLE
- [ ] Implementar prototipos de alta fidelidad enfocándose en la navegabilidad y usabilidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#14]

**Comment by aleospiria** [comment]
https://marvelapp.com/prototype/5bh2i85

**Comment by JohnFlorez25** [comment]
@aleospiria @sebastianVillada @dilantorre826 @DavidStiven15 recuerden agregar los niveles del juego y ques evidencie que la estructura del juego, es lo más importante de la aplicación hasta llegar al punto de que el usuario obtuvo puntos, esto es vital el día de la presentación
