### ISSUE TITLE
- [ ] Implementación en el Frontend haciendo uso de ReactJS evidenciando la navegación de acuerdo con los prototipos de alta fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#15]

**Comment by JohnFlorez25** [comment]
@aleospiria @sebastianVillada @dilantorre826 @DavidStiven15 para dentro 8 días deben evidenciar avances en esta actividad donde tengan las interfaces en REACTJS de lo que se validó en el prototipo en alta fidelidad y recomendaciones de los jurados en la socialización.
El código debe estar en el repositorio del proyecto (o sea este repositorio) validar con la profesora Laura y Dubenis para que les ayuden a realizar este proceso , les dejo un ejemplo de lo que se debe ir evidenciando.
![evidencia-repositorio](https://user-images.githubusercontent.com/22262727/94072375-26ce7e00-fdbb-11ea-9eaf-75a5bc8eae76.jpeg)

**Comment by DavidStiven15** [comment]
https://equipo4-fm-ppi20200.vercel.app

**Comment by JohnFlorez25** [comment]
@DavidStiven15 @aleospiria @sebastianVillada @dilantorre826 para dar cumplida esta actividad deben anexar en la wiki el video explicando la navegabilidad de las interfaces en reactjs

**Comment by DavidStiven15** [comment]
https://www.youtube.com/watch?v=18jd-FpAEyQ&t=3s

**Comment by DavidStiven15** [comment]
@JohnFlorez25  Listo profe, ya implemente el video en la wiki
