### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@aleospiria @sebastianVillada @dilantorre826 @DavidStiven15 El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend (Validar con la profesora dubenis)
[Formato Definición de los servicios backend.docx](https://github.com/JohnFlorez25/equipo4_fm_ppi2020/files/5272052/Formato.Definicion.de.los.servicios.backend.docx)

**Comment by JohnFlorez25** [comment]
@aleospiria @sebastianVillada @dilantorre826 @DavidStiven15 recuerden actualizar el documento con los servicios backend en la wiki

**Comment by DavidStiven15** [comment]
[Formato Definición de los servicios backend (1).docx](https://github.com/JohnFlorez25/equipo4_fm_ppi2020/files/5424750/Formato.Definicion.de.los.servicios.backend.1.docx)
