### ISSUE TITLE
- [ ] Diseño del modelo lógico de datos

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#18]

**Comment by DavidStiven15** [comment]
![Modelo_Relacional](https://user-images.githubusercontent.com/67077513/96355060-36cc3b80-10a3-11eb-8965-4b0ffcb6bad5.png)

**Comment by JohnFlorez25** [comment]
@DavidStiven15 por favor colocar esta imagen del modelo lógico de los datos en la wiki
