### ISSUE TITLE
- [ ] Construir los servicios principales del Backend que se deben implementar de acuerdo con las reglas de negocio y conectarlo con la Base de Datos

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#20]

**Comment by DavidStiven15** [comment]
[Formato Definición de los servicios backend (1).docx](https://github.com/JohnFlorez25/equipo4_fm_ppi2020/files/5396896/Formato.Definicion.de.los.servicios.backend.1.docx)

**Comment by JohnFlorez25** [comment]
@DavidStiven15 este formato debe ir es en DEFINICIÓN no en construcción

**Comment by JohnFlorez25** [comment]
@DavidStiven15 @aleospiria @sebastianVillada @dilantorre826 deben crear una carpeta llamada **backend** en el repositorio donde se cumpla como primera actividad la conectividad con la base de datos y el desarrollo de los servicios principales
