### ISSUE TITLE
- [ ] Hacer mapa de Historia de Usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo4_fm_ppi2020#9]

**Comment by aleospiria** [comment]
[mapa US.xlsx](https://github.com/JohnFlorez25/equipo4_fm_ppi2020/files/5059309/mapa.US.xlsx)

**Comment by JohnFlorez25** [comment]
@aleospiria La imagen no se muy bien, complementar y colocar la evidencia más ajustada para poder leer el texto de cada una de las historias en el mapa de historias
